### ISSUE TITLE
Cannot read source ROM file

### ISSUE THREAD

**Issue by glinesbdev** [Calindro/emulicious-debugger#1]
Hey! I just started with the emulicious emulator and it's been great so far. I also learned about your VS Code plugin and was very happy, but, I can't seem to get it working after going through the instructions. When hitting a breakpoint in the emulator and attaching the debugger in VS Code, I get the following error when stepping into the ROM code:

`Could not load source '/my_file_path/main.gb': Canceled.`

Any ideas would be greatly appreciated.

**Comment by Calindro** [comment]
Hi @glinesbdev, can you be more specific as to where you get this error? Is that shown in VS Code's editor? Maybe you can attach a screenshot? I think that would help greatly. :)

**Comment by glinesbdev** [comment]
Yes, sorry. Of course :) This is after I push the `step into` button after the header of the GB rom.

![image](https://user-images.githubusercontent.com/8079652/102820144-6563dc80-439a-11eb-872a-38d53215be7b.png)


![image](https://user-images.githubusercontent.com/8079652/102820018-2897e580-439a-11eb-9644-2af98547b8e6.png)

**Comment by Calindro** [comment]
I haven't seen this happen before. Would you mind sending me your project? If you don't won't to make it public, you can also send it to me via mail to info@emulicious.net

**Comment by glinesbdev** [comment]
Here is the repo to the code that I'm testing. It's a very basic "Hello World!" application: https://github.com/glinesbdev/gbz70-fun

**Comment by Calindro** [comment]
I don't think the issue is in your code but rather somewhere in your setup. To make sure, I just tried it with your code and it works fine for me.
So what I need to investigate the issue is the actual files that you're using. Including the project setup in .vscode for example.

**Comment by glinesbdev** [comment]
@Calindro I've update the repo to include those settings.

**Comment by Calindro** [comment]
Hmm that works fine for me as well. What version of VS Code do you use?

**Comment by glinesbdev** [comment]
Here is my application information
![image](https://user-images.githubusercontent.com/8079652/102917216-694f3780-444a-11eb-9107-a304f92db17c.png)

**Comment by Calindro** [comment]
Ok so the most recent. I just updated mine and even there it works. How do you start debugging? Via Run->Start Debugging (F5)? I'll try on Linux later to see if I can reproduce it there. In the meantime can you provide your Emulicious.ini?

**Comment by glinesbdev** [comment]
I either use the F5 key or click the Play arrow in the Debug pane next to `Attach to Emulicious`. Both give the same results. My ini file looks like:

```ini
#Emulicious settings file
#Tue Dec 22 13:34:39 CST 2020
WindowSoundViewerOpen=false
WindowSoundViewerY=614
WindowSoundViewerX=724
Update=2
OutlineWidth=112
RemoteDebuggingEnabled=true
GameBoyErrorBreakpointEnabled4=false
GameBoyErrorBreakpointEnabled3=false
WindowEmuliciousHeight=372
GameBoyErrorBreakpointEnabled2=false
GameBoyErrorBreakpointEnabled1=false
GameBoyErrorBreakpointEnabled0=true
ExpressionLines=1
RomDir=/Users/bradyn/dev/personal/gameboy/hello_world/build
WindowTileViewerHeight=411
StackWidth=592
WindowEmuliciousWidth=382
UninitializedMemoryBreakpointEnabled=false
InterruptBreakpointEnabled=false
WindowTileViewerOpen=true
Recent1=/Users/bradyn/Downloads/smooth-player.gb
UninitializedMemoryBreakpointCondition=
Recent0=/Users/bradyn/dev/personal/gameboy/hello_world/build/main.gb
WindowDebuggerWidth=774
WindowSoundViewerHeight=722
WindowDebuggerHeight=619
WindowDebuggerOpen=true
WindowDebuggerY=173
WindowDebuggerX=1204
WindowTileViewerY=921
WindowTileViewerX=1283
GameBoyErrorBreakpointCondition4=
WindowSoundViewerWidth=744
GameBoyErrorBreakpointCondition3=
InterruptBreakpointCondition=
WindowEmuliciousY=372
GameBoyErrorBreakpointCondition2=
WindowEmuliciousX=510
GameBoyErrorBreakpointCondition1=
GameBoyErrorBreakpointCondition0=
ReloadRomFileOnChange=true
WindowTileViewerWidth=516
```

**Comment by Calindro** [comment]
I noticed that you don't have a symbol file. You might want to add `-n main.sym` as commandline argument to `rgblink`. The symbol file helps with the sourcecode mapping.

You mentioned "Attach to Emulicious". For development I think in most cases "Launch in Emulicious" is preferable to "Attach to Emulicious". "Attach to Emulicious" is meant to be used when you want to attach VS Code to Emulicious while you are in the middle of debugging in Emulicious already. 🙂

Maybe these advices can already help to solve the issue.

**Comment by glinesbdev** [comment]
Adding those debugging symbols via `rgblink -n main.sym` and running launch instead of attach in VS code helped solve the issue! Thank you so much for your attention to this issue and helping me figure out what was going wrong 😄
