### ISSUE TITLE
Connection to the Emulicious failed

### ISSUE THREAD

**Issue by timmyraynor** [Calindro/emulicious-debugger#2]
Error message as follow:
Failed to connect to Emulicious Debugger after attempting to launch Emulicious.
Please contact the author about this error.
Until this is fixed, you can just start Emulicious yourself and enabled Remote Debugging from Emulicious's Tools menu before trying to launch a program.

Also tried with manual remote debugging enabling -> attach to Emulicious, still end up with failure

**Comment by Calindro** [comment]
What error did you get with the manual option?

Did you also try a different port?

Edit: Is your version of Emulicious up-to-date? You can check that in `Help->Configure Updates->Check for Updates`.

**Comment by timmyraynor** [comment]
Version is up-to-date for Emulicious.
Steps I setup:
- Add debug flag for lcc command, can see the corresponding cdb file created
-  Run java -jar emujar gbfile
-  in VS code, CMD + SHIFT + P -> attach to Emulicious
Got error message:
Failed to attach to Emulicious Debugger.
Please make sure that Emulicious is running and Remote Debugging is enabled in Emulicious's Tools menu.

Also I tried to launch a debug session in Emulicious, with a config file or without. I can see the Emulicious been launched but again get the previous mentioned message about contacting the Author.

**Comment by Calindro** [comment]
You mentioned CMD, so you are on Mac OS?

When you open the menu Tools->Remote Debugging, there is a disabled menu entry at the bottom for troubleshooting. Does it say `Listening`?

Do you see anything logged in your terminal? Any exceptions?

**Comment by timmyraynor** [comment]
Yep I am on MacOS.
It is showing Listening and I tried to open up another one while the one was running I can see the port is occupied.
Also, I checked the java program regarding the port in used, it is the default port: 58870

I did not see any exceptions or errors from my java command terminal (Emulicious)

**Comment by Calindro** [comment]
Is there something that might forbid a connection to localhost on that port? A firewall maybe?

**Comment by timmyraynor** [comment]
is there a way I could turn on debugging logs for the extension?
I am using a home computer, which I don't really think having much firewall settings

**Comment by Calindro** [comment]
Hmm VS Code is an Electron app so it has the same development tools as Chrome. You can open the console and see if any error is getting logged there.

**Comment by timmyraynor** [comment]
Double checked the debugger was not able to connect is due to seeking "localhost", if I add localhost entry to the /etc/hosts it will work with the attach.

**Comment by Calindro** [comment]
I'm glad you managed to solve it! Would you mind to elaborate a bit more? I'd like to fully understand the issue and the fix so I can either find a reliable solution or at least can give hints when someone else encounters the same issue.

So was `localhost` completely missing from `/etc/hosts`? And you could fix it by defining `localhost` as `127.0.0.1`?
Do you happen to know why it would be missing? Is it maybe missing there by default? Or did you maybe use some tool that might have removed it?

**Comment by timmyraynor** [comment]
Hi Calindro,
This might due to another tool I used to switch profiles of /etc/hosts which might removed my settings of localhost within the file, and also within MAC it seems the localhost is not a default hostname that points to 127.0.0.1. 
Might be better if you could check both(127.0.0.1 and localhost) rather than only localhost?

**Comment by Calindro** [comment]
It's VS Code using `localhost` but I saw that I can explicitly specify a `host`. So I should be able to work around it. :)
