### ISSUE TITLE
Local variables not showing

### ISSUE THREAD

**Issue by timmyraynor** [Calindro/emulicious-debugger#3]
Hi I hit some issues when I was trying to use the plugin, the debugger managed to step through the tasks but I cannot inspect any local variables defined in the function.
<img width="1335" alt="Screen Shot 2022-02-17 at 7 04 59 pm" src="https://user-images.githubusercontent.com/4987247/154432249-012d59ad-5ce7-4071-a3c8-4bf26a3a2019.png">

Is there something wrong with my configurations that I could try to avoid? Cause in the higher stack functions I can see some local vars displaying.
<img width="333" alt="Screen Shot 2022-02-17 at 7 07 38 pm" src="https://user-images.githubusercontent.com/4987247/154432392-a2255f4f-1a46-43ba-baa7-a14b5167764f.png">

**Comment by Calindro** [comment]
It's hard to tell from the screenshots alone. If you could zip up the whole folder of your project, I would be happy to investigate this and let you know. You can send it to me via Discord or via email (info@emulicious.net). Or if you don't mind sharing it publicly, I believe you could even attach it to this issue.

(When I get the whole folder, if there is something wrong with the generated files.)

**Comment by Calindro** [comment]
I just tried with another GBDK project and local variables worked just fine.
Can you ensure that you generate debug symbols? You should be able to find a non-empty .cdb file. If there is no .cdb file or if it's empty, you need to pass `-debug` to every call to `lcc` in order to properly generate debug symbols.

If that does not help, I'm afraid without your files, I'm not able to figure out what's wrong.

**Comment by basxto** [comment]
Which version of GBDK and SDCC? And did you (re)build everything with debug symbols? Does any function from this file show local variables?

**Comment by timmyraynor** [comment]
actually, I noticed I cannot replicate the issue since I redownload the files from my repo, please close this ticket for now maybe better to report it later once I am able to replicate the issue and also can capture more details around it. Thanks guys.
